[package]
name = "rs-blackbox"
version = "0.1.0"
authors = ["Ilya Epifanov <elijah.epifanov@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
nom = "6.1.0"
itertools = "0.10.0"
integer-encoding = "3.0.1"
chrono = "0.4.19"
ndarray = "0.14"
ndarray-stats = "0.4"

[dev-dependencies]
anyhow = "*"
